#  ___            ___
# /   \          /   \        
# \_   \        /  __/
#  _\   \      /  /__            
#  \___  \____/   __/
#      \_       _/
#        | @  @   \_
#        |                M A A G E N T A
#      _/     /\    
#     /o)  (o/\ \_
#     \_____/ /
#       \____/           

# This configuration is thinked for receiving mail (no sending)

# Users Table (Aliases)
table accounts file:/etc/mail/accounts
table domains  file:/etc/mail/domains

listen on 0.0.0.0

# Action performed when receive mail
# Not using maildir (which is simpler) because permission issues
# (700 by default and 750 is needed)
action "receive" mda "/usr/local/bin/deliver.sh %{dest.domain} %{dest.user}" virtual <accounts>

# Rules
match from any for domain <domains> action "receive"
match for local action "receive"
